Fix lint issue in Ubuntu Sanity
It seems that a lot of build failed with Ubuntu Sanity,
due to the following error:
```
Traceback (most recent call last):
  File "check_load_py_test.py", line 91, in <module>
    main()
  File "check_load_py_test.py", line 85, in main
    '\n'.join(files_missing_load)))
RuntimeError: The following files are missing load("//tensorflow:tensorflow.bzl", "py_test").
This load statement is needed because otherwise pip tests will try to use their dependencies, which are not visible to them.:
 tensorflow/contrib/input_pipeline/BUILD
tensorflow/contrib/periodic_resample/BUILD
```

This fix is an attempt to fix the issue

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>